### ISSUE TITLE
Missing Method

### ISSUE THREAD

**Issue by klaussantana** [PHPiotr/observer#1]
Hello, I was seeing your code and found some inconsistency in these files: `Observable1.php`, `Observable2.php` and `Observable3.php`. In line 8 you use `$subject->getData()` when you require `$subject` to be an instance of `SplSubject` in line 6. It happens that `SplSubject` doesn't has the `getData` method. Instead, you should use your own `Subject` class in line 6.

https://github.com/PHPiotr/observer/blob/295c313445c61fa5c0ee27762ffc086eb6fe7275/Observer1.php#L6
https://github.com/PHPiotr/observer/blob/295c313445c61fa5c0ee27762ffc086eb6fe7275/Observer1.php#L8

Your line 6 should be something like this:
`public function update ( Subject $subject )`

Now it's granted that your 8'th line will work, because your `Subject` class has the `getData` method and `$subject` is forced to be of this same `Subject` class.

**Comment by PHPiotr** [comment]
Good point. Would you like to open a PR for this one?

**Comment by PHPiotr** [comment]
@klaussantana How about that?
